/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidacionInfoUsuarioIndexRouteImport } from './routes/validacion-info-usuario.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidacionInfoUsuarioIndexRoute =
  ValidacionInfoUsuarioIndexRouteImport.update({
    id: '/validacion-info-usuario/',
    path: '/validacion-info-usuario/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/validacion-info-usuario/': typeof ValidacionInfoUsuarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/validacion-info-usuario': typeof ValidacionInfoUsuarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/validacion-info-usuario/': typeof ValidacionInfoUsuarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/validacion-info-usuario/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/validacion-info-usuario'
  id: '__root__' | '/' | '/validacion-info-usuario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValidacionInfoUsuarioIndexRoute: typeof ValidacionInfoUsuarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validacion-info-usuario/': {
      id: '/validacion-info-usuario/'
      path: '/validacion-info-usuario'
      fullPath: '/validacion-info-usuario/'
      preLoaderRoute: typeof ValidacionInfoUsuarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValidacionInfoUsuarioIndexRoute: ValidacionInfoUsuarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
